<?php 
ob_start();
require_once 'header_link.php';  
$obj = new cls_func();
require('../fpdf/fpdf.php');
class PDF extends FPDF
{
	function Header()
	{
		
		$this ->SetFont('Times','B',18);;
		$this->Cell(200,10,invoiceCompanyTitle(),0,0,'C');
		$this->Ln(6);

		$this ->SetFont('Times','',11);;
		$this->Cell(200,10,invoiceCompanyAddress(),0,0,'C');
		$this->Ln(5);

		$this ->SetFont('Times','',11);;
		$this->Cell(200,10,invoiceCompanyPhone(),0,0,'C');
		$this->Ln(5);

		$this ->SetFont('Times','',11);;
		$this->Cell(200,10,invoiceCompanyEmail(),0,0,'C');
		$this->Ln(9);
	}

	function Footer()
	{
	    $this->SetY(-15);
	    $this->SetFont('Times','I',8);
	    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
	}
}
$account=$_GET['ac_number'];
$fromdate=$_GET['fromdate'];
$todate=$_GET['todate'];

$from_date=$_GET['fromdate'];
$to_date=$_GET['todate'];

$pdf = new PDF();
$pdf->AddPage();
$pdf->AliasNbPages();

$pdf->SetFont('Times','B',13);	
$pdf->Cell(190,10,"Transaction Report From (".date("d-M-Y", strtotime($from_date)).") To (".date("d-M-Y", strtotime($to_date)).")",0,0,'C');
$pdf->Ln(10);


$pdf->SetFont('Times','',12);	
$pdf->Cell(110,6,"Accounts Number:",0,0,'R');
$pdf->SetFont('Times','B',13);	
$pdf->Cell(60,6,$account,0,0,'L');
$pdf->Ln(14);

$pdf->SetFont('Times','B',12);	
$pdf->Cell(32,8,"Transaction Date",1,0,'C');
$pdf->Cell(31,8,"Account No",1);
$pdf->Cell(31,8,"Transaction ID",1);
$pdf->Cell(31,8,"Description",1,0,'C');
$pdf->Cell(30,8,"Type",1,0,'C');
$pdf->Cell(30,8,"Amount",1,0,'C');
$pdf->Ln();
                           
$i=0;
$ex_tot = 0;

$results = $obj->selectran($account,$fromdate,$todate);
$trow=count($results);
if($trow>0){
	foreach($results as $tran) {
	   $total = 0;
	   
	           
	            $total += $tran["amount"];
	      
		

	  	$ex_tot+=$total;

		$pdf->SetFont('Times','',11);	
		$pdf->Cell(32,8,date("d-m-Y", strtotime($tran["date"])),1,0,'C');
		$pdf->Cell(31,8,$tran["account_number"],1,0,'L');
		$pdf->Cell(31,8,$tran["transaction_id"],1);
		$pdf->Cell(31,8,$tran["description"],1);
		$pdf->Cell(30,8,$tran["type"],1,0,'C');
		$pdf->Cell(30,8,$tran["amount"].' tk',1);
		$pdf->Ln();
	}

	$pdf->SetFont('Times','B',14);
	$pdf->Cell(132,8,"","");
	$pdf->Cell(24,8,"Total",1);
	$pdf->Cell(29,8,$ex_tot." TK",1,0,'C');
	$pdf->Ln(12);

$pdf->SetFont('Times','',12);	
$pdf->Cell(160,2,"Generated by: :",0,0,'R');
$pdf->SetFont('Times','B',13);	
$pdf->Cell(60,2,$_SESSION['adminFullName'],0,0,'L');

}else{
	$pdf->SetFont('Arial','B',12);	
	$pdf->Cell(190,10,"",'c');
	$pdf->Ln();

	$pdf->SetFont('Times','B',12);	
	$pdf->Cell(190,10,"No data available",1,'c');
	$pdf->Ln();
}
$pdf->Output();
ob_end_flush(); 
?>